### ISSUE TITLE
Inaccessible buttons when trying to edit “Processo de negócio”

### ISSUE THREAD

**Issue by silva-eduardo** [ffquintella/netrisk#38] opened 2023-12-19 14:46 UTC
When trying to edit a “Processo de negócio”, the buttons are not visible for activation. The issue occurs in this area and not in others due to the number of “Unidades Organizacionais” displayed on the screen. Similar to Issue #34.

**Comment by ffquintella** [comment] 2024-01-02 12:52
cannot reproduce please contact me to show a sample

**Comment by ffquintella** [comment] 2024-01-02 13:32
Will be fixed on next version

**Closed by ffquintella** 2024-01-02 13:32 UTC
Labels: bug
